from .mouse import (
    click,
    double_click,
    right_click,
    scroll_up,
    scroll_down,
)

from .keyboard import (
    type_text,
    press_key,
    hotkey,
    key_down,
    key_up,
    enter,
    backspace,
    delete,
    tab,
    escape,
    space,
    copy,
    paste,
    cut,
    undo,
    redo,
    select_all,
    save,
    find,
    new_tab,
    close_tab,
    reopen_tab,
    switch_tab,
    refresh,
    screenshot_shortcut,
    task_manager,
    lock_screen,
    show_desktop,
    alt_tab,
    close_window,
    screenshot
)


from .window import (
    minimize_window,
    maximize_window,
    restore_window,
    switch_window,
    next_window,
    show_desktop,
    snap_left,
    snap_right,
    move_window_to_next_monitor,
    open_task_view,
    create_virtual_desktop,
    close_virtual_desktop,
    next_virtual_desktop,
    previous_virtual_desktop,
    get_active_window,
    list_windows,
    focus_window
)